// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIDs
{
        public const string achievement_racing_first_victory = "CgkI9ZbZnpIHEAIQBQ"; // <GPGSID>
        public const string leaderboard_victory_num = "CgkI9ZbZnpIHEAIQCA"; // <GPGSID>
        public const string leaderboard_racing_complete_time = "CgkI9ZbZnpIHEAIQBg"; // <GPGSID>
        public const string leaderboard_mix_amount = "CgkI9ZbZnpIHEAIQCg"; // <GPGSID>
        public const string achievement_first_schedule_start = "CgkI9ZbZnpIHEAIQBA"; // <GPGSID>
        public const string leaderboard_possession_part_amount = "CgkI9ZbZnpIHEAIQCQ"; // <GPGSID>
        public const string achievement_store_random_box_sell = "CgkI9ZbZnpIHEAIQAw"; // <GPGSID>
        public const string leaderboard_possession_money = "CgkI9ZbZnpIHEAIQBw"; // <GPGSID>
        public const string achievement_game_start = "CgkI9ZbZnpIHEAIQAQ"; // <GPGSID>
        public const string achievement_store_random_box_purchase = "CgkI9ZbZnpIHEAIQAg"; // <GPGSID>

}

